### ISSUE TITLE
Upgrade Manifest Version

### ISSUE THREAD

**Issue by alfarhanzahedi** [alfarhanzahedi/ytviews#1]
The extension is currently using v2.0 which is deprecated. Its support will be removed in 2023. We need to move to v3.0. Further details can be found at https://developer.chrome.com/blog/mv2-transition/.

**Comment by jatinpandey77** [comment]
I will take this up!

**Comment by jatinpandey77** [comment]
Updated manifest and validated that the extension is working properly.
